<?php
/*
 * Koin Module - payment method module for Magento, integrating
 * the billing forms with Koin Web Service.
 * Copyright (C) 2013  Koin
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * @Last update		2014-18-12
 * @Autor     	Elder Xavier
 * @Email		eldersxavier@gmail.com / desenv@e-lustre.com.br 
 */
?>

<fieldset class="form-list">
	<ul id="payment_form_V3W_Koin_Standard" style="display:none; margin-top: -30px;">
	<li style="width: 80%; float: left; margin-top:10px">	
		<div class="koin_products" >
			<input type="hidden" name="payment[koin_fraud_id]" id="payment[koin_fraud_id]" value="" />			
			<script type="text/javascript">
				GetKoinFraudID(function (FraudId) { document.getElementById('payment[koin_fraud_id]').value = FraudId; });
			</script>
			<div class="koin-clear"></div>
		</div>

		
		<?php
		$inputs = $this->getFormInputs();
		if (count($inputs) > 0){
			?>
			<div id="koin_form_fisica" style="display:none;">
				<?php 
				foreach ($inputs['fisica'] as $input){
					echo "{$input['label']}:<br/>";
					echo "<input type='text'";
						echo " value=''";
						echo " name='payment[{$input['name']}]'";
						echo " id='{$input['name']}'";
						echo ($input['options']) ? " {$input['options']}" : "";
						echo " class='required-entry'";
					echo "/>";
				}
				?>
			</div>
			<div id="koin_form_juridica" style="display:none;" class="form">
				<?php 
				foreach ($inputs['juridica'] as $input){
					echo "{$input['label']}:<br/>";
					echo "<input type='text'";
						echo " value=''";
						echo " name='payment[{$input['name']}]'";
						echo " id='{$input['name']}'";
						echo ($input['options']) ? " {$input['options']}" : "";
						echo " class='required-entry'";
					echo "/>";
				}
				?>
			</div>
			<div class="koin-clear"></div>
			
			<script type="text/javascript">
				function dateMask(inputData, e){
					if(document.all){
						var tecla = event.keyCode;
					} else {
						var tecla = e.which;
					}
					if(tecla >= 47 && tecla < 58){
						var data = inputData.value;
						if (data.length == 2 || data.length == 5){
							data += '/';
							inputData.value = data;
						}
					} else if(tecla == 8 || tecla == 0){
						return true;
					} else {
						return false;
					}
				}
		
				var idInputCpf = '';
				var idInputCnpj = '';
				
				<?php
				$idInputCpfCnpj = $this->getIdCpfCnpjInput();
				if ($idInputCpfCnpj['id_input_cpf']){
					?>
					idInputCpf = '<?php echo $idInputCpfCnpj['id_input_cpf'];?>';
					<?php
				}
				if ($idInputCpfCnpj['id_input_cnpj']){
					?>
					idInputCnpj = '<?php echo $idInputCpfCnpj['id_input_cnpj'];?>';
					<?php
				}
				?>

				window.setTimeout(autoCompleteCpfCnpj,0);
		    	window.setTimeout(verificarTipoPessoa,0);
		
		    	(function(){
		    		if (idInputCpf != ''){
						if (document.getElementById(idInputCpf) != undefined && document.getElementById('koin_cpf') != undefined){
							$(idInputCpf).observe('blur',autoCompleteCpfCnpj);
						}
		        	}
		    		if (idInputCnpj != ''){
		        		if (document.getElementById(idInputCnpj) != undefined){
		        			var inputCnpj = document.getElementById(idInputCnpj);
		
			        		//mesmo ID (OSC)
			        		if (idInputCpf == idInputCnpj){
			            		if ($$('input[id="'+idInputCnpj+'"]')[1] != undefined){
			        				inputCnpj = $$('input[id="'+idInputCnpj+'"]')[1];
			            		}
			            	}
			            	
							if (document.getElementById('koin_cnpj') != undefined){
								inputCnpj.observe('blur',autoCompleteCpfCnpj);
							}
			        	}
		    		}
		    	})();
			</script>
			<?php 
		}
		
		
		if ($this->exibirTermo()){
			?>
 		Escolha a Koin e pague pelo produto somente após recebê-lo.<br>
                    Essa opção de pagamento não altera o prazo de entrega nem gera custo adicional.<br>
                    Você receberá um e-mail da Koin com as instruções para o pagamento.<br>
                    Em caso de dúvidas, acesse <a href="http://www.koin.com.br" target="_blank">www.koin.com.br</a>.
			<div class="koin_termo" id="koin_termo">
				<input type='checkbox' class='required-entry check_termo' name='koin_termo_aceite' id='koin_termo_aceite' value="1" onchange="checkTermo()" />
				<input type='hidden' class='check_termo' name='payment[koin_termo_aceite]' id='payment[koin_termo_aceite]' value="0" />

				<label for="koin_termo_aceite">Li e aceito os <a href="javascript:void(0)" onclick="showTermo()">Termos e Condições</a>.</label>
				<div class="koin-clear"></div>
				
				
				<div class="two_fields_">
					<div class="short">
						<label for="billing:month" class="" id="id_label_dob_koin"> Data de nascimento * </label>					
						<div class="data_area customer-dob"> 
							<div class="dob-day">
								<input maxlength="2" type="text" id="koin_billing_day" name="koin_billing_day" value="" title="Dia" class="required-entry"  />
								<label for="koin_billing_day">DD</label>
							</div>
							<div class="dob-month">
								<input maxlength="2" type="text" id="koin_billing_month" name="koin_billing_month" value="" title="M&ecirc;s" class="required-entry"  />
								<label for="koin_billing_month">MM</label>
							</div>
							<div class="dob-year">
								<input maxlength="4" type="text" id="koin_billing_year" name="koin_billing_year" value="" title="Ano" class="required-entry" />
								<label for="koin_billing_year">AAAA</label>
							</div>							
						</div>
					</div>
				</div>
				
			</div>			
			<script type="text/javascript">
			<?php /*caso cliente logado, atualiza aniversario*/
			if ($this->helper('customer')->isLoggedIn() ):
				$customer = Mage::getSingleton('customer/session');
				$lentaxvat = strlen($customer->getCustomer()->getTaxvat());
				if($lentaxvat > 11){
				?>
					document.getElementById("id_label_dob_koin").innerHTML = "Data de fundação *";
				<?php	
				}						
				?>
				function persistenceBirtday(){
					$j('#loading-mask').css('display','block');
					jQuery.ajax({
					type      : 'post', 
					url       : 'http://dev.e-lustre.com.br/_persistente_birtday_koin.php',
					data	  : 'email=<?php echo $customer->getCustomer()->getEmail();?>'+'&day='+document.getElementById("koin_billing_day").value + '&mont='+document.getElementById("koin_billing_month").value+'&year='+document.getElementById("koin_billing_year").value, 	
					dataType  : 'html', 
					success: function( txt ){							
						setTimeout(function(){			
							$j('#loading-mask').css('display','none');																		
						}, 1000);
					}				
			});
			}
			$j('#koin_billing_year').change(function(){
				if(document.getElementById("koin_billing_day").value>0 && document.getElementById("koin_billing_month").value>0){
					persistenceBirtday();					
				}
			});
			$j('#koin_billing_month').change(function(){
				if(document.getElementById("koin_billing_day").value>0 && document.getElementById("koin_billing_year").value>0){
					persistenceBirtday();					
				}
			});
			$j('#koin_billing_day').change(function(){
				if(document.getElementById("koin_billing_month").value>0 && document.getElementById("koin_billing_year").value>0){
					persistenceBirtday();					
				}
			});
			
			<?php			
			endif;			
			?>
				
				$j('#koin_billing_day').change(function(){
					valor = $j('#koin_billing_day').val();
					document.getElementById("billing:day").value = valor;
				});
				
				$j('#koin_billing_month').change(function(){
					valor = $j('#koin_billing_month').val();
					document.getElementById("billing:month").value = valor;
				});
				$j('#koin_billing_year').change(function(){
					valor = $j('#koin_billing_year').val();
					document.getElementById("billing:year").value = valor;
				});
				
				$j("#koin_billing_day").mask("99");
				$j("#koin_billing_month").mask("99");
				$j("#koin_billing_year").mask("9999");				
			</script>
		<?php					
		}
		?>
		</li>
	</ul>
</fieldset>